version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: auctionshop
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_API_BASE_URL: http://localhost:8080/
  #   depends_on:
  #     - postgres
  #     - redis